#!/bin/bash

<<Step12
This script runs blastn so that I can fuse the output to the other files so that I can add this it to the final file. 
The previous step in this pipeline is: 3UTR_5UTR_exon_df_fusion_2024-4-3.ipynb (/home/administrator/Documents/Kaas/Venom_ncRNA_project/Scripts/Python/3UTR_5UTR_exon_df_fusion_2024-4-3.ipynb)
The next step in this pipeline is: 3UTR_5UTR_exon_df_fusion_2024-4-9.ipynb (/home/administrator/Documents/Kaas/Venom_ncRNA_project/Scripts/Python/blast_processing_2024-4-10.ipynb)
Step12

<<Makeblastdb
Prior to running this script, makeblast was run as follows:

makeblastdb -in /home/administrator/Documents/Kaas/Venom_ncRNA_project/Usable_data/miRBase/miRBase_database.fa -dbtype nucl -out /home/administrator/Documents/Kaas/Venom_ncRNA_project/Usable_data/miRBase/miRBase_database


Building a new DB, current time: 04/10/2024 01:29:58
New DB name:   /home/administrator/Documents/Kaas/Venom_ncRNA_project/Usable_data/miRBase/miRBase_database
New DB title:  /home/administrator/Documents/Kaas/Venom_ncRNA_project/Usable_data/miRBase/miRBase_database.fa
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 3000000000B
Adding sequences from FASTA; added 48885 sequences in 0.213972 seconds.

Makeblastdb

# Define variables for the file paths
    # Query fasta file generated by ShortStack and some formatting
    query="/home/administrator/Documents/Kaas/Venom_ncRNA_project/Usable_data/miRanda_mirna_inputs_from_shortstack/2024-4-9_Run/Post_clean/mature_mir.fasta"

    # Path to the database
    database="/home/administrator/Documents/Kaas/Venom_ncRNA_project/Usable_data/miRBase/miRBase_database"

    # Out file path
    outfile="/home/administrator/Documents/Kaas/Venom_ncRNA_project/Results/blast/mature_mir-miRBase_alignment.tab"

# Run blastn with the following options
blastn -task blastn-short \
    -query "${query}" \
    -db "${database}" \
    -out "${outfile}" \
    -outfmt 6