#!/bin/bash

<<Step10
This script runs blastn so that I can fuse the output to the other files so that I can add this it to the final file. 
The previous steps in the pipeline are: 3UTR_miranda.tab_bedtools_intersect_fusion_2024-5-13.ipynb (/home/administrator/Documents/Kaas/Venom_ncRNA_project/Scripts/Python/3UTR_miranda.tab_bedtools_intersect_fusion_2024-5-13.ipynb)
                                        5UTR_miranda.tab_bedtools_intersect_fusion_2024-5-13.ipynb (/home/administrator/Documents/Kaas/Venom_ncRNA_project/Scripts/Python/5UTR_miranda.tab_bedtools_intersect_fusion_2024-5-13.ipynb)
                                        CDS_miranda.tab_bedtools_intersect_fusion_2024-5-13.ipynb (/home/administrator/Documents/Kaas/Venom_ncRNA_project/Scripts/Python/CDS_miranda.tab_bedtools_intersect_fusion_2024-5-13.ipynb)
The next step in this pipeline is: blast_processing_2024-5-13.ipynb (/home/administrator/Documents/Kaas/Venom_ncRNA_project/Scripts/blast/blast_processing_2024-5-13.ipynb)
Step10

# Define variables for the file paths
    # Query fasta file generated by ShortStack and some formatting
    query="/home/administrator/Documents/Kaas/Venom_ncRNA_project/Usable_data/miRanda_mirna_inputs_from_shortstack/2024-5-13_Run/Post_clean/mature_mir.fasta"

    # Create path for miRBase_database.fa
    mirbase="/home/administrator/Documents/Kaas/Venom_ncRNA_project/Usable_data/miRBase/miRBase_database.fa"

    # Path to the database
    database="/home/administrator/Documents/Kaas/Venom_ncRNA_project/Usable_data/miRBase/miRBase_database"

    # Out file path
    outfile="/home/administrator/Documents/Kaas/Venom_ncRNA_project/Results/blast/miRBase/mature_mir-miRBase_alignment.tab"

# Run makeblastdb
#makeblastdb -in "$mirbase" -dbtype nucl -out "$database"


# Run blastn with the following options
blastn -task blastn-short \
    -query "${query}" \
    -db "${database}" \
    -out "${outfile}" \
    -outfmt 6